import type { Spec } from "./spec-schema";

export function specToMarkdown(spec: Spec): string {
  const lines: string[] = [];
  lines.push(`# ${spec.toolName}`);
  lines.push("");
  lines.push("> Generated by BuildScope · aibuildersclub.ai");
  lines.push("");

  lines.push("## Problem");
  lines.push(spec.problemStatement);
  lines.push("");

  lines.push("## Target user");
  lines.push(spec.targetUser);
  lines.push("");

  lines.push("## Inputs");
  spec.inputs.forEach((i) => lines.push(`- ${i}`));
  lines.push("");

  lines.push("## Outputs");
  spec.outputs.forEach((o) => lines.push(`- ${o}`));
  lines.push("");

  lines.push("## Workflow");
  spec.workflowSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  lines.push("");

  lines.push("## AI behavior");
  lines.push(spec.aiBehavior);
  lines.push("");

  lines.push("## Human checkpoints");
  spec.humanCheckpoints.forEach((c) => lines.push(`- ${c}`));
  lines.push("");

  lines.push("## First ugly version");
  lines.push(spec.firstUglyVersion);
  lines.push("");

  lines.push("## Success criteria");
  spec.successCriteria.forEach((c) => lines.push(`- ${c}`));
  lines.push("");

  lines.push("## Tech path");
  lines.push("**Stack:**");
  spec.techPath.stack.forEach((s) => lines.push(`- ${s}`));
  lines.push("");
  lines.push(`**Why:** ${spec.techPath.rationale}`);
  lines.push("");

  lines.push("## UI brief");
  lines.push(`**Layout:** ${spec.uiBrief.layout}`);
  lines.push("");
  lines.push("**Key screens:**");
  spec.uiBrief.keyScreens.forEach((s) => lines.push(`- ${s}`));
  lines.push("");
  lines.push("**Copy-paste prompt for v0 / Lovable / Cursor:**");
  lines.push("");
  lines.push("```");
  lines.push(spec.uiBrief.copyPastePrompt);
  lines.push("```");
  lines.push("");

  lines.push("## Sprint fit");
  lines.push(`**Score: ${spec.sprintFit.score} / 100**`);
  lines.push("");
  lines.push("**Why this is a good fit:**");
  spec.sprintFit.reasons.forEach((r) => lines.push(`- ${r}`));
  lines.push("");
  if (spec.sprintFit.risks.length) {
    lines.push("**Risks to watch:**");
    spec.sprintFit.risks.forEach((r) => lines.push(`- ${r}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "Want to actually build this? Apply for the next AI Builders Club sprint at aibuildersclub.ai."
  );

  return lines.join("\n");
}
